### ISSUE TITLE
fig.align='center' messes up full-width plots

### ISSUE THREAD

**Issue by Felixmil** [nstrayer/tuftesque2#12]
When chunk option is set to `fig.align='center' `, the full-width plots get unwanted extra margin on the left.

![image](https://user-images.githubusercontent.com/34234913/56991493-1bf8c500-6b98-11e9-8345-db3f0b88e9f2.png)

**Comment by nstrayer** [comment]
Oh good catch! I'd imagine this comes from some css property that I left untouched in the `full_width_img` class.

**Comment by nstrayer** [comment]
Fixed this in 47fe8e7684ccc1ea5da201d30f6d343601e3b693. 

The problem was `fig.align` was adding `style = "margin: 0; and display: block;"` to the plots `img` tag. To get around this I added a `opts_hook` for `fig.align` that watches for the combo of `fig.align = 'center'`, and `class = 'full-width-plot'` and simply sets `fig.align = 'default'` instead.
